config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'restaurants/index'
  get 'restaurants/show'
  get 'restaurants/edit'
  get 'restaurants/new'
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
            # message: 'Please enter "chinese", "italian", "japanese", "french", or "belgian".'
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  # def edit
  # end

  # def update
  #   @restaurant = Restaurant.update(restaurant_params)
  #   if @restaurant.save
  #     redirect_to :restaurants_path
  #   else
  #     render :edit
  #   end
  # end

  # def destroy
  #   @restaurant.destroy
  #   redirect_to restaurants_path
  # end


  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews.reviews
  end
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<!--     <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<%= link_to "add another restaurant", restaurants_new_path %>
<p><%= @restaurants.length %></p>
<% @restaurants.each do |restaurant| %>
  <h1><%= link_to restaurant.name, restaurants_show_path(@restaurant) %></h1>
  <p><%= restaurant.phone_number %></p>
  <p><%= restaurant.address %></p>
  <p><%= restaurant.category %></p>
<% end %>

app/views/restaurants/new.html.erb
<h1>Enter a new restaurant</h1>
<%= simple_form_for [@restaurant] do |form| %>
<%= form.input :name %>
<%= form.input :address %>
<%= form.input :phone_number %>
<%= form.input :category %>
<%= form.submit "Add"%>
<% end %>

app/views/restaurants/show.html.erb
  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.phone_number %></p>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.category %></p>

<%= link_to "add a review", new_restaurant_review_path(@restaurant) %>
<%= link_to "go home", restaurants_path %>

<h1>Reviews</h1>
<% @reviews.each do |review| %>
  <p><%= review.content %></p>
  <p><%= review.rating %></p>
<% end %>

app/views/reviews/new.html.erb
<h1>Enter a review</h1>
<%= simple_form_for [@restaurant, @review] do |form| %>
<%= form.input :content %>
<%= form.input :rating %>
<%= form.submit "Add"%>
<% end %>